version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aparavi-rag-app
    image: raul-hybrid-multimodal-rag-app:0.1.0
    env_file: .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      DATASET_DIR: /app/SampleDataSet
      EVAL_FORCE_OPENAI: ${EVAL_FORCE_OPENAI:-0}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-DEBUG}
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-neo4j_password_change_me}
      NEO4J_BOLT_URI: ${NEO4J_BOLT_URI:-bolt://neo4j:7687}
      NEO4J_HTTP_URI: ${NEO4J_HTTP_URI:-http://neo4j:7474}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./:/app
      - ./SampleDataSet:/app/SampleDataSet:ro
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: ["uvicorn","src.api:app","--host","0.0.0.0","--port","8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20

  neo4j:
    image: neo4j:5.24-community
    container_name: aparavi-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4j_password_change_me}
      - NEO4J_PLUGINS=["apoc","bloom"]
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_http_listen__address=:7474
      - NEO4J_server_bolt_listen__address=:7687
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 1' | cypher-shell -u ${NEO4J_USER:-neo4j} -p ${NEO4J_PASSWORD:-neo4j_password_change_me} >/dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aparavi-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: aparavi-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-plugins:
  pg-data:
